name: Build Game for Linux
on:
  push:
    branches: [ main, develop ]
  workflow_dispatch:
jobs:
  Linux:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          submodules: true

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.6

      - name: Installing Dependencies
        run: sudo apt-get install libvlc-dev libvlccore-dev vlc-bin vlc --fix-missing

      - name: Install Libraries
        run: |
          haxelib install hmm --quiet
          haxelib run hmm install --quiet
          haxelib run lime rebuild hxcpp
          haxelib run lime rebuild systools linux

      - name: Compile
        run: haxelib run lime build linux

      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: linuxBuild
          path: export/release/linux/bin
          if-no-files-found: error
